name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public-folder
          path: public

  deploy:
    runs-on: ubuntu-latest
    
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: public-folder
          path: public

      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod




# name: Digaos Blog
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '12'
#       - uses: actions/upload-artifact@v1
#         with:
#           name: public-folder
#           path: public

#       - name: Install Dependencies
#         run: |
#           npm install # or any other build commands you need

#       - name: Build and Test
#         run: |
#           npm run build # or your build command

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: Atifact Download
#         uses: actions/download-artifact@v1
#         with:
#           name: public-folder
#       #S3 Sync-action
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1 # Change this to your desired AWS region
#           SOURCE_DIR: 'public'

#       - name: Deploy to S3
#         run: |
#           aws s3 sync ./build s3://your-s3-bucket-name
